<?php

namespace App\Filament\Admin\Resources\VisitTransfer\VisitingRemovals\Pages;

use App\Filament\Admin\Helpers\Pages\BaseListRecordsPage;
use App\Filament\Admin\Resources\VisitTransfer\VisitingRemovals\VisitingRemovalResource;

class ListVisitingRemovals extends BaseListRecordsPage
{
    protected static string $resource = VisitingRemovalResource::class;

    protected function getHeaderActions(): array
    {
        return [];
    }

    public function getSubheading(): ?string
    {
        return 'Automatically generated by the system when a visiting controller is inactive for 6 months, or inactive twice within a 2-year period.';
    }
}
