#!/bin/bash

echo "Running pre-commit lint hook"

files=$(git diff --cached --name-only --diff-filter=ACM)
files=$(echo "$files" | grep "\.php$")

echo "Running lint on the following files: $files"

composer lint $files
