ServerName core.test

<VirtualHost *:80>
    ServerName core.test
    DocumentRoot /workspace/public

    <Directory /workspace/public>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
