 codecov:
  branch: master
  
comment: false

coverage:
  status:
    project:
      default: off
      events_jobs_queues:
        target: 100%
        flags: events_jobs_queues
      exceptions:
        target: 100%
        flags: exceptions
      http:
        target: 100%
        flags: http
      models:
        target: 100%
        flags: models
      notifications:
        target: 100%
        flags: notifications
    patch:
      target: 100%
      only_pulls: true
      flags: events_jobs_queues, exceptions, http, models, notifications

flags:
  events_jobs_queues:
    paths:
      - app/Events
      - app/Jobs
  exceptions:
    paths:
      - app/Exceptions
    ignore:
      - app/Exceptions/Handler.php
  http:
    paths:
      - app/Http
    ignore:
      - app/Http/Kernel.php
  models:
    paths:
      - app/Models/Entities
      - app/Models/Pivots
      - app/Models/Traits
      - app/Models/Services
  notifications:
    paths:
      - app/Notifications
      - app/Mail
  tests:
    paths:
      - tests/
