preset: laravel

risky: false

enabled:
    - "align_equals"
    - "align_double_arrow"

disabled:
    - "unalign_equals"

finder:
  exclude:
    - "tests"

  name:
    - "*.php"

  not-name:
    - "*blade.php"
    - "_ide_helper.php"