[supervisord]
nodaemon = true
user = root
logfile = /dev/null
logfile_maxbytes = 0
pidfile = /tmp/supervisord.pid

[unix_http_server]
file = /tmp/supervisor.sock
chown = vscode:vscode

[supervisorctl]
serverurl = unix:///tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:apache]
command = /usr/local/bin/apache2-foreground
autostart = true
autorestart = true
stopasgroup = true
killasgroup = true
startretries = 20
stdout_logfile = /dev/stdout
stdout_logfile_maxbytes = 0
stderr_logfile = /dev/stderr
stderr_logfile_maxbytes = 0
