version: 1
update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - ""

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    default_labels:
      - ""

  - package_manager: "php:composer"
    directory: "/nova-components/WaitingListsManager"
    update_schedule: "weekly"
    default_labels:
      - ""

  - package_manager: "javascript"
    directory: "/nova-components/WaitingListsManager"
    update_schedule: "weekly"
    default_labels:
      - ""
