-- -----------------------------------------------------------------------------
-- Database Initialisation Script
-- -----------------------------------------------------------------------------
--
-- This script is automatically executed by the official MySQL Docker image
-- when the database is created for the first time.
--
-- Why is this file here?
--
-- When the MySQL container starts with an empty data directory, it looks for
-- SQL files inside:
--
--     /docker-entrypoint-initdb.d
--
-- Docker Compose mounts the local "mysql_init" folder into this location:
--
--     ./mysql_init -> /docker-entrypoint-initdb.d
--
-- Every .sql file in that directory is executed in alphabetical order.
--
-- This file is named "01-database.sql" so that it runs before any other SQL
-- files that may create tables or insert data.
--
-- For example:
--
--     01-database.sql
--     02-schema.sql
--     03-seed-data.sql
--
-- This ensures the required databases already exist before anything attempts
-- to create tables within them.
--
-- Important:
--
-- This script normally runs ONLY when MySQL is initialising a brand-new,
-- empty database volume.
--
-- If the Docker volume already contains data, MySQL assumes the database has
-- already been set up and will NOT execute these initialisation scripts again.
--
-- If you need these scripts to run again during development, you can remove
-- the existing database volume (which will also delete all stored data):
--
--     docker compose down -v
--
-- or:
--
--     docker volume rm <volume-name>
--
-- -----------------------------------------------------------------------------
-- Create the application's databases
-- -----------------------------------------------------------------------------
--
-- Create the "core" database if it does not already exist.
--
-- The "IF NOT EXISTS" clause prevents MySQL from producing an error if the
-- database is already present.
CREATE DATABASE IF NOT EXISTS `core`;

-- Create the "cts" database if it does not already exist.
--
-- Having multiple databases allows different parts of the application to keep
-- their data logically separated while still being managed by the same MySQL
-- server.
CREATE DATABASE IF NOT EXISTS `cts`;

-- -----------------------------------------------------------------------------
-- Grant database permissions
-- -----------------------------------------------------------------------------
--
-- GRANT gives database users permission to perform actions.
--
-- In this case:
--
--     ALL PRIVILEGES
--
-- means the user can perform almost every database operation, including:
--
--     - creating databases
--     - creating tables
--     - inserting data
--     - updating records
--     - deleting records
--     - modifying database structures
--
-- "*.*" means:
--
--     Every database
--     Every table
--
-- 'root' is MySQL's built-in administrator account.
--
-- '%' is a wildcard meaning the user may connect from any host.
--
-- This is convenient for local Docker development because other containers,
-- such as the PHP application or phpMyAdmin, can connect without restriction.
--
-- WARNING:
--
-- This configuration is intended for local development only.
--
-- Granting ALL PRIVILEGES to the root user from any host would not normally be
-- appropriate for a production environment, where access should be restricted
-- and applications should use dedicated database accounts with only the
-- permissions they actually require.
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
