name: Devcontainer

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".devcontainer/**"

concurrency:
  group: devcontainer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Build devcontainer & run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build and test in dev container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: php artisan test --parallel --processes=4 --recreate-databases
