name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Environment File
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Write Nova Secrets
      env:
        NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
        NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
      run: |
        cp auth.json.example auth.json
        sed -i "s/your-username/${NOVA_USERNAME}/g" auth.json
        sed -i "s/your-password/${NOVA_PASSWORD}/g" auth.json
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate App Key
      run: php artisan key:generate
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Databases
      run: |
        mysql -e 'create database IF NOT EXISTS core;' -uroot
        mysql -e 'create database IF NOT EXISTS core_testing;' -uroot
        mysql -e 'create database IF NOT EXISTS cts;' -uroot
    - name: Execute PHPUnit Tests
      run: vendor/bin/phpunit
