name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Environment File
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Write Nova Secrets
      env:
        NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
        NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
      run: |
        cp auth.json.example auth.json
        sed -i "s/your-username/${NOVA_USERNAME}/g" auth.json
        sed -i "s/your-password/${NOVA_PASSWORD}/g" auth.json
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate App Key
      run: php artisan key:generate
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Databases
      env:

      run: |
        sudo /etc/init.d/mysql start
        sudo apt-get install -y mysql-client
        mysql -e  -uroot -proot 'create database IF NOT EXISTS core;'
        mysql -e  -uroot -proot 'create database IF NOT EXISTS core_testing;'
        mysql -e  -uroot -proot 'create database IF NOT EXISTS cts;'
    - name: Execute PHPUnit Tests
      run: vendor/bin/phpunit
