name: Laravel Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Environment File
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Write Nova Secrets
      env:
        NOVA_USERNAME: ${{ secrets.NOVA_USERNAME }}
        NOVA_PASSWORD: ${{ secrets.NOVA_PASSWORD }}
      run: |
        cp auth.json.example auth.json
        sed -i "s/your-username/${NOVA_USERNAME}/g" auth.json
        sed -i "s/your-password/${NOVA_PASSWORD}/g" auth.json
    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Install Nova
      run: |
        php artisan nova:install
        cd nova-components/WaitingListsManager && composer install && cd ../../
    - name: Generate App Key
      run: php artisan key:generate
    - name: Cache Routes
      run: php artisan route:cache
    - name: Cache Config
      run: php artisan config:cache
    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Databases
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE IF NOT EXISTS core;' -h127.0.0.1 -uroot -proot
        mysql -e 'CREATE DATABASE IF NOT EXISTS core_testing;' -h127.0.0.1 -uroot -proot
        mysql -e 'CREATE DATABASE IF NOT EXISTS cts;' -h127.0.0.1 -uroot -proot
    - name: Execute PHPUnit Tests
      run: vendor/bin/phpunit
